### ISSUE TITLE
Cannot find module 'app-root-path' with npm

### ISSUE THREAD

**Issue by wallet77** [michaeldegroot/mysql-cache#25]
Hello,

When I start my node script I got this error : Cannot find module 'app-root-path' 
It seems module "app-root-path" cannot be found when trying to install mysql-cache with npm install.

In package.json file "app-root-path"  module is in dev dependencies, it's probably the error's root cause ;)

It's only happen with version 1.0 and higher. We start with version 0.5 without problem.

**Comment by michaeldegroot** [comment]
That's really funny, something my continuous integration didn't pick up.

Thanks for the heads up! fixed in 1f91fc8 and updated at the npm repository to version 1.1.6

The shame :D
