### ISSUE TITLE
NodeJS Module Caching Problem

### ISSUE THREAD

**Issue by p0d3r** [michaeldegroot/mysql-cache#28]
Since NodeJS caches modules by using require function, we're not able to create two different connections.

For example, I got two javascript classes, one for general use, one for chat specific. If I try to require mysql-cache on any other class file, first created mysql.init configuration are used.

To avoid this issue, we should be able to create new module instances.

After that anyone should be able to use module like so:

```
var MysqlCache = require('mysql-cache');
var mysql = new MysqlCache();
mysql.init(config);
```
or 
`var mysql = new MysqlCache(config);`

**Comment by michaeldegroot** [comment]
Great idea, I will implement this when I have the time for it :)

**Comment by AliPoder** [comment]
Perfect, thank you. Please consider that since this is a major update, it should has backward compability or it should released as a new major version.

**Comment by michaeldegroot** [comment]
Yes good thinking, no worries!

**Comment by michaeldegroot** [comment]
It all worked out, I changed the major version because all old code will break now thanks to init/start not being active anymore

You now create a new mysqlCache instance like so:

`// Require mysqlCache
const MysqlCache = require('mysql-cache')

// Create a new instance with settings
const mysql = new MysqlCache({
    host: '127.0.0.1',
    // Other settings etc...
})

// Listen for the connected event, this means you are ready to send queries
mysql.event.on('connected', () => {
    mysql.query('SELECT 133 + 7 AS solution', (err, result, mysqlCache) => {
        if (err) {
            throw new Error(err)
        }
        // Do something with the results
    })
})`

what do you think?

**Comment by AliPoder** [comment]
Perfect! I've just updated the package, and run some tests and it works as expected. Very clean coding here, thank you for your efforts. I also have some other things in mind, but i cannot remember right now, i'll open issues as they come. 

BTW, we should be able to specify host and port for Redis too.

Thanks!

**Comment by michaeldegroot** [comment]
Thank you, your idea was really good, so you also have the honours for making this a better package!

> BTW, we should be able to specify host and port for Redis too.

Yes, good catch, I will add it to the todo =)

i'm looking forward to your ideas!
