### ISSUE TITLE
Should be able to request an update on cache

### ISSUE THREAD

**Issue by p0d3r** [michaeldegroot/mysql-cache#32]
Anyone may want to update current cache with actual results. 

For example, if i update my profile information then refresh the page, sql query result will be outdated. To avoid this, i could add a boolean key to my current session object and pass it to the Database class when requesting for the same query so it wont return cached results.

Actually I already did this on code for my needs but I don't want to send a pull request for not to mess things up. Here is what I did:

- Assigned `dbQuery`'s callback to a const.
- Added an if/else check if `sql` variable has `updateCache` property, inside `dbProviderResult` where it's `true`.
- If `sql` has a property called `updateCache` and it's set to `true`, run `dbQuery`, if it's not just run old `hit` code and pass the `dbProviderResult` to `cb`.

**Comment by michaeldegroot** [comment]
To understand you: you want to invalidate a cache key? isn't [delKey](https://github.com/michaeldegroot/mysql-cache#delkey-idparams) sufficient for this?

to quote from that page: `This exact SQL is now removed from the cache. Making sure the next time this query is executed it will be retrieved from the database.`

**Comment by p0d3r** [comment]
If I choose to use delKey, I need to pass sql query and params among methods which I think is not a good design and they also may be dynamic. So yeah, `updateResult` param will be good.

**Comment by michaeldegroot** [comment]
Implemented in https://github.com/michaeldegroot/mysql-cache/commit/f2c8bf24d6c6ca22d6caefd9482d49773a43de44 (npm version 2.1.0)
