### ISSUE TITLE
mysql connect is not a function

### ISSUE THREAD

**Issue by HamzaDevz** [michaeldegroot/mysql-cache#34]
Hello,

First, Thanks for your awesome job !

But, when i do :

`var mysql = new MysqlCache(config);`
`mysql.connect(.....);`

I got this error : `TypeError: mysql.connect is not a function`

**Comment by HamzaDevz** [comment]
The right mysql object is inside of the instance MysqlCache.

Readme is up to date ?

**Comment by michaeldegroot** [comment]
Hi!

Are you sure you are running the latest version of mysql-cache? version 2.1.0?

**Comment by HamzaDevz** [comment]
My mistake i was running with the 2.0.2 !

Thanks again !
