### ISSUE TITLE
Cache Zones

### ISSUE THREAD

**Issue by michaeldegroot** [michaeldegroot/mysql-cache#36]
1. Call a query `SELECT * FROM users WHERE id = 1`
2. set the zone to `USER_CREDITS_**1**` when calling this query
3. after each update call (or a when you update the user credits w/e), use a clear cache zone function to clear all caches with the zone name `USER_CREDITS_**1**`
4. When  `SELECT * FROM users WHERE id = 1` is called again it will be retrieved from database because zone was cleared.

**Comment by p0d3r** [comment]
Where do these keys will store? Please consider load balancing of a node server.

**Comment by michaeldegroot** [comment]
these cache zone objects will be stored in the cacheProvider itself, they will be stored on a different branch so it will not conflict with existing mysql caches. The zone object will be a object with key name as the zone itself holding a array with strings containing the actual mysql cache keys. 

It should be good.

**Comment by p0d3r** [comment]
What if update/delete query runs on a different instance of mysql-cache instead of select query made? I suppose it wont change anything since keys stored in cacheProvider, right?

**Comment by michaeldegroot** [comment]
> What if update/delete query runs on a different instance of mysql-cache instead of select query made? I suppose it wont change anything since keys stored in cacheProvider, right?

Correct

> I mean, think that we have separated every route like users.js for /users, projects.js for /projects, I initialized a new instance of mysql-cache in each route file.

It should be no problem
