### ISSUE TITLE
cache not clearing on process in cluster mode

### ISSUE THREAD

**Issue by harshitj2005** [michaeldegroot/mysql-cache#5]
hi,

i have implement this module to cache my mysql result for ttl of 1 day. I have also created API for clearing cache using flushAll method.
now my app is running in cluster mode having 4 threads as the I/O is very fast. now when i clear the cache using my app api it is executed properly but the cache is not cleared from all the threads. i got to know this as my read api is showing different result on every call. please help me out to resolve this issue asap

**Comment by michaeldegroot** [comment]
Thank you for opening this issue.

It seems the [cluster-node-cache](https://www.npmjs.com/package/cluster-node-cache) could be a good candidate for a replacement of [node-cache](https://www.npmjs.com/package/node-cache) 

I will do some testing when I have time for it. In the mean time you could try to implement it yourself and if you want send a pull request if it's working :)

**Comment by michaeldegroot** [comment]
I have found https://github.com/PaquitoSoft/memored which seems to be perfect for this problem. My testing with cluster-node-cache was unsuccessfu. I hope memored will prove to be useful for us

**Comment by michaeldegroot** [comment]
Implemented in 971f032 this should be gooood

**Comment by michaeldegroot** [comment]
I could not get this to work properly, closing this issue for now :(

**Comment by michaeldegroot** [comment]
(removed older messaged for clarity)

This is now possible thanks to  the new feature cacheProviders: https://github.com/michaeldegroot/mysql-cache#new-in-version-100-rocket

if in clustered mode checkout the cache provider: mmap or redis
